# Generated by Django 3.1.12 on 2025-07-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('description', models.TextField()),
                ('responsibilites', models.TextField()),
                ('skills_required', models.TextField()),
                ('apply_link', models.URLField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
