# Generated by Django 3.1.12 on 2025-07-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='responsibilites',
            new_name='responsibilities',
        ),
    ]
