# Generated by Django 5.2.4 on 2025-09-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250722_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roadmap',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
